-- ============================================================================
-- MULTI-SESSION ORCHESTRATION SCHEMA
-- Revolutionary: 1 PROJECT = MULTI-SESSION with AI-powered handoff
-- ============================================================================

-- Projects table (same as before, but enhanced for session-centric approach)
CREATE TABLE IF NOT EXISTS projects (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  description TEXT,
  status TEXT NOT NULL DEFAULT 'active', -- active, paused, completed
  
  -- Session-centric stats
  total_sessions INTEGER NOT NULL DEFAULT 0,
  total_credits_used INTEGER NOT NULL DEFAULT 0,
  
  -- Master handoff (stores latest compressed context)
  master_handoff_id INTEGER,
  
  -- Infinite growth loop metrics
  growth_efficiency REAL DEFAULT 0.0, -- 0.0 to 1.0
  context_preservation_rate REAL DEFAULT 0.0, -- 0.0 to 1.0
  
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Sessions table (CORE: Each session represents one execution cycle)
CREATE TABLE IF NOT EXISTS sessions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  project_id INTEGER NOT NULL,
  
  -- Session identification
  session_number INTEGER NOT NULL, -- 1, 2, 3, ... (sequential per project)
  session_type TEXT DEFAULT 'development', -- development, research, debugging, deployment
  
  -- Account used (optional - can be NULL for single-account projects)
  account_id INTEGER,
  account_name TEXT, -- Store for historical reference even if account deleted
  
  -- Session timing
  started_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  completed_at DATETIME,
  duration_minutes INTEGER,
  
  -- Session objectives & outcomes
  objectives TEXT, -- What this session aims to achieve
  accomplishments TEXT, -- What was actually accomplished
  blockers TEXT, -- Any blockers or issues encountered
  
  -- Credit usage
  credits_used INTEGER DEFAULT 0,
  credits_efficiency REAL DEFAULT 0.0, -- 0.0 to 1.0 (optimal: 0.88-0.92)
  
  -- Status
  status TEXT NOT NULL DEFAULT 'in_progress', -- in_progress, completed, failed, paused
  
  -- Handoff linkage
  previous_handoff_id INTEGER, -- Link to previous session's handoff
  generated_handoff_id INTEGER, -- Link to handoff generated by this session
  
  -- AI-powered features
  ai_confidence REAL DEFAULT 0.0, -- AI handoff generation confidence (0.0-1.0)
  
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  
  FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
  FOREIGN KEY (previous_handoff_id) REFERENCES handoff_documents(id),
  FOREIGN KEY (generated_handoff_id) REFERENCES handoff_documents(id)
);

-- Handoff Documents (GAME CHANGER: AI-generated master prompts)
CREATE TABLE IF NOT EXISTS handoff_documents (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  project_id INTEGER NOT NULL,
  session_id INTEGER NOT NULL, -- Which session generated this handoff
  
  -- Handoff content
  handoff_type TEXT DEFAULT 'ai_generated', -- ai_generated, manual, hybrid
  
  -- Master prompt (compressed context)
  master_prompt TEXT NOT NULL, -- The full master handoff prompt
  compressed_context TEXT, -- Additional compressed details
  
  -- Structured data
  accomplishments_json TEXT, -- JSON array of accomplishments
  blockers_json TEXT, -- JSON array of blockers
  next_steps_json TEXT, -- JSON array of next steps
  technical_notes TEXT, -- Technical details & decisions
  
  -- AI metadata
  ai_model TEXT, -- Which AI model generated this (e.g., 'meta-llama/Meta-Llama-3.1-8B-Instruct')
  ai_confidence REAL DEFAULT 0.0,
  compression_ratio REAL, -- How much was compressed (0.0-1.0)
  
  -- Usage tracking (infinite growth loop)
  times_used INTEGER DEFAULT 0, -- How many times this handoff was loaded
  success_rate REAL DEFAULT 0.0, -- 0.0-1.0 based on subsequent session outcomes
  
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  
  FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
  FOREIGN KEY (session_id) REFERENCES sessions(id) ON DELETE CASCADE
);

-- Conversation History (stores full conversation for AI training & handoff generation)
CREATE TABLE IF NOT EXISTS conversation_history (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  session_id INTEGER NOT NULL,
  
  turn_number INTEGER NOT NULL, -- Sequential order (1, 2, 3, ...)
  role TEXT NOT NULL, -- 'user', 'assistant', 'system'
  content TEXT NOT NULL,
  
  timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
  
  FOREIGN KEY (session_id) REFERENCES sessions(id) ON DELETE CASCADE
);

-- Accounts table (optional - for multi-account orchestration)
CREATE TABLE IF NOT EXISTS accounts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  account_name TEXT NOT NULL,
  account_email TEXT,
  platform TEXT DEFAULT 'genspark', -- genspark, cursor, etc.
  
  credits_available INTEGER DEFAULT 100,
  credits_used_today INTEGER DEFAULT 0,
  
  specialization TEXT, -- e.g., 'frontend', 'backend', 'fullstack'
  status TEXT DEFAULT 'available', -- available, active, exhausted, inactive
  
  last_used_at DATETIME,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Knowledge Base (reusable patterns, solutions, best practices)
CREATE TABLE IF NOT EXISTS knowledge_base (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  
  category TEXT NOT NULL, -- 'pattern', 'solution', 'troubleshooting', 'best_practice'
  title TEXT NOT NULL,
  description TEXT,
  content TEXT NOT NULL,
  
  tags TEXT, -- Comma-separated tags
  
  -- Usage metrics
  usage_count INTEGER DEFAULT 0,
  success_rate REAL DEFAULT 0.0,
  
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Project Files (track file changes across sessions)
CREATE TABLE IF NOT EXISTS project_files (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  project_id INTEGER NOT NULL,
  session_id INTEGER, -- Which session created/modified this file
  
  file_path TEXT NOT NULL,
  file_type TEXT, -- 'source', 'config', 'documentation', etc.
  file_size INTEGER,
  
  -- Change tracking
  change_type TEXT, -- 'created', 'modified', 'deleted'
  lines_added INTEGER DEFAULT 0,
  lines_removed INTEGER DEFAULT 0,
  
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  
  FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
  FOREIGN KEY (session_id) REFERENCES sessions(id) ON DELETE SET NULL
);

-- ============================================================================
-- INDEXES FOR PERFORMANCE
-- ============================================================================

CREATE INDEX IF NOT EXISTS idx_sessions_project ON sessions(project_id);
CREATE INDEX IF NOT EXISTS idx_sessions_status ON sessions(status);
CREATE INDEX IF NOT EXISTS idx_sessions_started_at ON sessions(started_at DESC);

CREATE INDEX IF NOT EXISTS idx_handoff_project ON handoff_documents(project_id);
CREATE INDEX IF NOT EXISTS idx_handoff_session ON handoff_documents(session_id);

CREATE INDEX IF NOT EXISTS idx_conversation_session ON conversation_history(session_id);
CREATE INDEX IF NOT EXISTS idx_conversation_timestamp ON conversation_history(timestamp DESC);

CREATE INDEX IF NOT EXISTS idx_accounts_status ON accounts(status);
CREATE INDEX IF NOT EXISTS idx_accounts_platform ON accounts(platform);

CREATE INDEX IF NOT EXISTS idx_knowledge_category ON knowledge_base(category);
CREATE INDEX IF NOT EXISTS idx_knowledge_usage ON knowledge_base(usage_count DESC);

CREATE INDEX IF NOT EXISTS idx_files_project ON project_files(project_id);
CREATE INDEX IF NOT EXISTS idx_files_session ON project_files(session_id);

-- ============================================================================
-- TRIGGERS FOR AUTO-UPDATE timestamps
-- ============================================================================

CREATE TRIGGER IF NOT EXISTS update_projects_timestamp 
AFTER UPDATE ON projects
BEGIN
  UPDATE projects SET updated_at = CURRENT_TIMESTAMP WHERE id = NEW.id;
END;

CREATE TRIGGER IF NOT EXISTS update_sessions_timestamp 
AFTER UPDATE ON sessions
BEGIN
  UPDATE sessions SET updated_at = CURRENT_TIMESTAMP WHERE id = NEW.id;
END;

CREATE TRIGGER IF NOT EXISTS update_handoff_timestamp 
AFTER UPDATE ON handoff_documents
BEGIN
  UPDATE handoff_documents SET updated_at = CURRENT_TIMESTAMP WHERE id = NEW.id;
END;

CREATE TRIGGER IF NOT EXISTS update_accounts_timestamp 
AFTER UPDATE ON accounts
BEGIN
  UPDATE accounts SET updated_at = CURRENT_TIMESTAMP WHERE id = NEW.id;
END;

CREATE TRIGGER IF NOT EXISTS update_knowledge_timestamp 
AFTER UPDATE ON knowledge_base
BEGIN
  UPDATE knowledge_base SET updated_at = CURRENT_TIMESTAMP WHERE id = NEW.id;
END;
